salesforcecli/plugin-user

src/commands/force/user/display.ts
test/commands/user/display.test.ts

fix: fix json output, fixed alias @ W-8590775@

---

src/commands/force/user/display.ts
test/commands/user/display.test.ts

fix: table output and alias @W-8590775@

---

src/commands/force/user/display.ts
test/commands/user/display.test.ts

fix: alias actual alias

---

src/commands/force/user/create.ts
src/commands/force/user/display.ts
test/commands/user/create.test.ts

fixes an issue when the config file and other properties passed in weren't matching due to a capitalization difference
@W-8659187@

fix: standardized capitalization issues with config file

---

src/commands/force/user/create.ts
yarn.lock

fix(create.ts): param should be setalias not alias

---

package.json

Need to add force topic to fix CLI Ref generation. 
@W-8718585@

fix: add force topic

---

.gitignore
messages/create.json
src/commands/force/user/create.ts
src/commands/force/user/list.ts
src/commands/force/user/password/generate.ts
test/commands/user/create.test.ts
test/commands/user/list.test.ts
test/commands/user/password/generate.test.ts
yarn.lock

saves encrypted password to the authfile
@W-8776193@

chore: save encrypted password to authfile

---

package.json

fix: bump to 1.0.9 to release

---

messages/display.json
src/commands/force/user/display.ts
test/commands/user/display.test.ts

looks for access token and throws with a helpful error message instead of retrieving running the command but return a bunch of `Unknown` in the output.
@W-8583923@

fix: error message for display + accessToken

---

package.json

fix: 1.0.11

---

messages/create.json
messages/display.json
messages/list.json
messages/password.generate.json

Updates help for the force:user* commands.
@W-8721871@

fix: update help for force:user* commands

---

src/commands/force/user/create.ts
test/commands/user/create.test.ts

changes json output to match previous/smoke tests
@W-8865019@

fix: user:create matches smoke test json [skip-validate-pr]

---

.circleci/config.yml

CI only tests for CTC
@W-7869694@

fix: still releases w/ CTC from main branch

---

.circleci/config.yml

verifies we can repeat npm-releases from same repo/scheduled build
@W-7869694@

test: can repeat-release

---

src/commands/force/user/create.ts
src/commands/force/user/display.ts
src/commands/force/user/password/generate.ts

fixes errors associate with https://app.circleci.com/pipelines/github/salesforcecli/plugin-user/676/workflows/b567bf2b-a924-4f19-9bc1-8954f12e3c14/jobs/2158
@W-9329741@

refactor: don't overwrite base properties

---

messages/display.json
src/commands/force/user/display.ts

What does this PR do?
adds security warning for the output of user:display (AT on screen)
What issues does this PR fix or reference?
@W-9953835@

feat: add security warning

---

package.json
src/commands/force/user/create.ts
src/commands/force/user/display.ts
src/commands/force/user/permset/assign.ts
yarn.lock

I for one welcome our new compiler overlords
@W-10054614@

refactor: fix TS update errors

---

package.json
src/commands/force/user/create.ts
yarn.lock

Use boolean parser from kit (moved from plugin-user to kit here: https://github.com/forcedotcom/kit/pull/25)
**DEPENDS ON:** https://github.com/forcedotcom/kit/pull/25
@W-8865618@

chore: use boolean parser from kit

---

.circleci/config.yml

add context for circle

---

bin/dev
bin/dev.cmd
bin/run
package.json
src/commands/force/user/create.ts
src/commands/force/user/display.ts
src/commands/force/user/list.ts
src/commands/force/user/password/generate.ts
src/commands/force/user/permset/assign.ts
src/commands/force/user/permsetlicense/assign.ts
test/commands/user/create.nut.ts
test/commands/user/create.test.ts
test/commands/user/display.test.ts
test/commands/user/list.test.ts
test/commands/user/password/generate.test.ts
test/commands/user/permset/assign.test.ts
test/commands/user/permsetlicense/assign.test.ts
test/tsconfig.json
yarn.lock

parking-orbit plugin-user
command5/core3
@W-10743901@

fix: parking orbit plugin-user

---

messages/create.json
messages/display.json
messages/list.json
messages/password.generate.json
messages/permset.assign.json
messages/permsetlicense.assign.json

Adds prompt to examples so they're correctly tagged during CLI Ref generation
@W-11164018@

Add prompt to examples

---

package.json
src/commands/force/user/create.ts
src/commands/force/user/display.ts
src/commands/force/user/list.ts
src/commands/force/user/password/generate.ts
src/commands/force/user/permset/assign.ts
src/commands/force/user/permsetlicense/assign.ts
test/commands/user/create.test.ts
test/commands/user/display.test.ts
test/commands/user/list.test.ts
test/commands/user/password/generate.test.ts
test/commands/user/permset/assign.test.ts
test/commands/user/permsetlicense/assign.test.ts
yarn.lock

Use `StateAggregator` instead of `GlobalInfo`
Depends on https://github.com/forcedotcom/sfdx-core/pull/587
@W-11214501@

feat: use StateAggregator

---

package.json
test/commands/user/create.nut.ts
test/commands/user/create.test.ts
yarn.lock

re-enable permission set assignment NUT, it was disabled when parking-orbiting the plugin, cli-testkit v2 uses core v3 so it now passes.
https://github.com/salesforcecli/plugin-user/pull/319#discussion_r856622390
also re-enabled a UT that was being skipped.
@W-11171863@

test: re-enable permission set assignment NUT

---

package.json
test/allCommands.nut.ts
test/allCommandsNoJSON.nut.ts
test/commands/user/create.nut.ts
test/commands/user/permsetlicense/assign.nut.ts
yarn.lock

Use latest cli-plugins-testkit
@W-11823417@

chore: use latest testkit

---

README.md
command-snapshot.json
package.json
tsconfig.json
yarn.lock

[@W-12085135@](https://gus.my.salesforce.com/apex/ADM_WorkLocator?bugorworknumber=W-12085135)

Parking orbit cleanup

---

package.json
yarn.lock

Bump the version of @salesforce-core to get user:create working with access token auth.
@W-11659812@

fix: bump core version for bug fix

---

package.json

applies sf styles to topic descriptions in package.json
@W-12490016@

fix: apply sf styles to topic desc

---

package.json
test/commands/create.nut.ts
yarn.lock

Changes execCmd on nuts back to use double quotes
[skip-validate-pr]

Back to double quotes on NUT

---

messages/create.md
messages/display.md
messages/list.md
messages/password.generate.md
messages/permset.assign.md
messages/permsetlicense.assign.md

Fixes a message that still referred to an sfdx-style command, and cleans up a few more things. 
@W-13191393@

fix: clean up messages/examples

---

package.json

remove
chore: remove unused dev plugin

chore: remove unused dev plugin

---

package.json
test/allCommands.nut.ts
test/commands/permsetlicense/assign.nut.ts
test/forceCommands.nut.ts
yarn.lock

test: expect nonZero exit code

---

package.json
yarn.lock

fix(deps): plugins-core 7 (esm)

---

README.md
command-snapshot.json
package.json
test/df17AppBuilding/data/Volunteer_Event__cs.json
test/df17AppBuilding/data/masterImportPlan.json
yarn.lock

Add `--flags-dir` to all commands by bumping @salesforce/sf-plugins-core to v8
[skip-validate-pr]

feat: bump sf-plugins-core

---

messages/permset.assign.md
messages/permsetlicense.assign.md

Removes implication from --help that the commands work only on scratch orgs. 
@W-17774366@

W-17774366:  Update help for "org assign permset|license"
